version: '3.4'

services:
  app:
    image: moviesapi
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=devlopment
    environment:
      - NODE_ENV=devlopment
      - moviesApi_jwtPrivateKey=example_moviesApi_jwtPrivateKey
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules

    command: npm run dev