version: '3.4'

services:
  app:
    image: moviesapi
    build:
      context: .
      dockerfile: ./Dockerfile
      args:
        - NODE_ENV=devlopment
    environment:
      - PORT=3000
      - MONGO_URL=mongodb://mongo-db:27017/
      - moviesApi_jwtPrivateKey=example_moviesApi_jwtPrivateKey
    ports:
      - 3000:3000
    volumes:
      - ./:/usr/src/app
      - /usr/src/app/node_modules
    depends_on:
      - mongo-db
    command: npm run dev

  mongo-db:
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - moviesapi-mongo-data-dev:/data/db
volumes:
  moviesapi-mongo-data-dev: